// //This is an example of objects
        // function Module(code, name, lecturer) {
        //     this.code = code;
        //     this.name = name;
        //     this.lecturer = lecturer;
        //     this.students = [];
        
        //     this.addStudent=function(studentName) {
        //       this.students.push(studentName);
        //     }
        //   }

        //   let cmt120 = new Module('cmt120', 'fundamentals of programming', 'martin');

        //   cmt120.addStudent("Vikram");
        //   cmt120.addStudent("Ponnuswamy");
        //   console.log(cmt120);